// Code generated by docs-gen. DO NOT EDIT.
package cmd

// cobra-doc-start
var docsCobraMapping = map[string]string{
	`exclude-kinds`: `List all kinds to be excluded`,
	`include-kinds`: `List all kinds to be included`,
	`created-within`: `The max allowed age duration for the resources`,
	`lists`: `Export as lists instead of individual files`,
	`target`: `The target directory`,
	`clear-target`: `Clear the target directory before exporting`,
	`summary`: `If enabled, a summary is printed`,
	`progress`: `Progress mode bar|bubbles|simple|none`,
	`namespace`: `A single namespace (default all)`,
	`include-cluster-resources`: `Export cluster-scoped resources too, when a namespace filter is active`,
	`worker`: `The number of parallel worker`,
	`archive`: `Create a tar.gz archive`,
	`otlp-metrics`: `OTLP Metrics are enabled`,
	`quiet`: `Output is prevented`,
	`verbose`: `Errors during export are listed in summary`,
	`size`: `Print the size of the exported files`,
}

func cflagVar[T any](p *T, name string, value T) (pOut *T, nameOut string, valueOut T, reason string) {
	return p, name, value, docsCobraMapping[name]
}

func cflag[T any](name string, value T) (nameOut string, valueOut T, reason string) {
	return name, value, docsCobraMapping[name]
}

func cflagP[T any](name, shorthand string, value T) (nameOut, shorthandOut string, valueOut T, reason string) {
	return name, shorthand, value, docsCobraMapping[name]
}

// cobra-doc-end
