name: e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://hub.docker.com/r/kindest/node/tags
        k8s_version: [ "v1.28.13", "v1.29.8", "v1.30.4" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install kind with registry
        uses: bakito/kind-with-registry-action@main
        with:
          node_image: kindest/node:${{ matrix.k8s_version }}
          kubectl_version: ${{ matrix.k8s_version }}

      - name: Run Exporter
        run:  go run . --config config.yaml --progress bar >> $GITHUB_STEP_SUMMARY
