name: Scan GitHub Release with VirusTotal

on:
  release:
    types: [released]
  push:
    branches: [vt]

jobs:
  scan_release:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze Build Assets
        uses: bakito/virustotal-action@main
        with:
          #release_name: ${{github.event.release.tag_name}}
          release_name: v0.6.3
          vt_api_key: ${{secrets.VT_API_KEY}}