name: Scan GitHub Release with VirusTotal

on:
  release:
    types: [released]
  schedule:
    - cron: '45 3 * * *'
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to scan (optional, defaults to latest)'
        required: false
        default: ''

jobs:
  scan_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Tag
        id: latest_release
        run: |
          RELEASE_TAG=${{ github.event.release.tag_name }}
          if [ -z "$RELEASE_TAG" ]; then
            RELEASE_TAG=${{ github.event.inputs.release_tag }}
          fi
          if [ -z "$RELEASE_TAG" ]; then
            RELEASE_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          fi
          echo "tag_name=$RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: Analyze Build Assets
        uses: bakito/virustotal-action@f27c5bc29fedcfc124c12e1c37a91bfb0a20276f # v1.0.3
        with:
          release_name: ${{ steps.latest_release.outputs.tag_name }}
          vt_api_key: ${{secrets.VT_API_KEY}}
